# Generated by Django 3.2.25 on 2026-06-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'acquisition type',
                'verbose_name_plural': 'acquisition types',
            },
        ),
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'business area',
                'verbose_name_plural': 'business areas',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'owner',
                'verbose_name_plural': 'owners',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.FileField(blank=True, null=True, upload_to='icons/')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('decommissioned', models.BooleanField(default=False, verbose_name='decommissioned')),
                ('targetQuantity', models.IntegerField(blank=True, null=True, verbose_name='target quantity')),
                ('depreciation', models.BooleanField(default=False, verbose_name='deprecation')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='datasheets/', verbose_name='datasheet')),
                ('inUse', models.BooleanField(default=False, verbose_name='in use')),
                ('supplier', models.TextField(blank=True, verbose_name='supplier')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('ean', models.IntegerField(blank=True, null=True, verbose_name='EAN')),
                ('premium', models.BooleanField(default=False, verbose_name='premium')),
                ('unlabeled', models.BooleanField(default=False, verbose_name='unlabeled')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image')),
                ('contact', models.TextField(blank=True, verbose_name='contact')),
                ('permanentLoan', models.BooleanField(default=False, verbose_name='permanent loan')),
                ('business_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.businessarea', verbose_name='business area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.owner', verbose_name='owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_parents', to='inventory.item', verbose_name='parent')),
                ('tag', models.ManyToManyField(to='inventory.Tag', verbose_name='tags')),
                ('temp_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_temp_parents', to='inventory.item', verbose_name='temporal parent')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Elimination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('revenue', models.IntegerField(help_text='Please use the following format: <em>Money in Cent</em>.', verbose_name='Revenue')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'elimination',
                'verbose_name_plural': 'eliminations',
            },
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'verbose_name': 'barcode',
                'verbose_name_plural': 'barcodes',
            },
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('unitPrice', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.acquisitiontype')),
            ],
            options={
                'verbose_name': 'acquisition',
                'verbose_name_plural': 'acquisitions',
            },
        ),
    ]
